apiVersion: apps/v1
kind: Deployment
metadata:
  name: swaggerdefgen
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: swaggerdefgen 
  template:
    metadata:
      labels:
        app: swaggerdefgen
    spec:
      containers:
      - image: docker.io/namanarora/swaggerdefgen 
        name: swaggerdefgen
        ports:
          - containerPort: 8000
